### ISSUE TITLE
How is d-spacing calculated without knowing the lattice parameters?

### ISSUE THREAD

**Issue by hmparanjape** [beamteamco/davis#5]
One question - to calculate the d-spacing you need to know lattice parameters 'a', 'b', 'c'.
1/d^2 = (h^2 + k^2 + l^2)/a^2

How is d calculated right now?

**Comment by apetersen0** [comment]
Within the refinement app or the xrViewer app? In the xrViewer app, it uses the equation
d = lambda/(2 \* sin(theta/2)) to convert the 2theta values (note theta in the equation represents the 2theta values) to d-spacing. This equation was taken from Bragg's law where 2 \* d \* sin(theta) = n*lambda. In the refinement app, it uses your initial guess for the lattice parameters to calculate and show the d-spacing lines. It also uses those values as a starting point for the least squares refinement to determine the actual lattice parameter. The "radialCompute.m" file contains the conversion equations for the xrViewer app, and the "xrViewer_LatParmRefine.m" and "LatParmResid2.m" contains the relevant calculations for the refinement tool. "LatParmResid2.m" contains the equation you mentioned in your comment, and is used for the least squares refinement (in this case is replaces d with 2theta values for the minimization, and modifies the equation accordingly).
